### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by anotheri** [elastic/apm-nodejs-http-client#105]
I'm getting this error not sure why, please advice:
```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at truncateCustomKeys (/cache/node_modules/elastic-apm-http-client/lib/truncate.js:309:23)
    at truncateCustomKeys (/cache/node_modules/elastic-apm-http-client/lib/truncate.js:316:22)
    at Object.truncSpan [as span] (/cache/node_modules/elastic-apm-http-client/lib/truncate.js:136:12)
    at Client._encode (/cache/node_modules/elastic-apm-http-client/index.js:327:27)
    at Client.encodeObject (/cache/node_modules/elastic-apm-http-client/index.js:272:15)
    at Array.map (<anonymous>)
    at Client._writevCleaned (/cache/node_modules/elastic-apm-http-client/index.js:276:22)
    at processBatch (/cache/node_modules/elastic-apm-http-client/index.js:250:12)
    at Client._writev (/cache/node_modules/elastic-apm-http-client/index.js:268:3)
    at doWrite (/cache/node_modules/elastic-apm-http-client/node_modules/readable-stream/lib/_stream_writable.js:405:97)
    at clearBuffer (/cache/node_modules/elastic-apm-http-client/node_modules/readable-stream/lib/_stream_writable.js:501:5)
    at Client.Writable.uncork (/cache/node_modules/elastic-apm-http-client/node_modules/readable-stream/lib/_stream_writable.js:317:94)
    at Timeout._onTimeout (/cache/node_modules/elastic-apm-http-client/index.js:299:14)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by trentm** [comment]
@anotheri Sorry for the delay in responding. If you are still able to reproduce this, can you let us know what version of the package you are using and, ideally, some small code that can repro.
