### ISSUE TITLE
Throws error `Cannot read property 'length' of undefined` on StreamChopper.Writable.write()

### ISSUE THREAD

**Issue by SimonSimCity** [elastic/apm-nodejs-http-client#98]
I've discovered today that this library which under a certain circumstance throws the following errors by `readable-stream`:

```
 Uncaught Exception: TypeError: Cannot read property 'length' of undefined
     at writeOrBuffer (readable-stream/lib/_stream_writable.js:370:42)
     at StreamChopper.Writable.write (readable-stream/lib/_stream_writable.js:303:11)
     at Client._writevCleaned (elastic-apm-http-client/index.js:276:17)
     at processBatch (elastic-apm-http-client/index.js:249:12)
     at Client._writev (elastic-apm-http-client/index.js:267:3)
     at doWrite (readable-stream/lib/_stream_writable.js:405:97)
     at clearBuffer (readable-stream/lib/_stream_writable.js:501:5)
     at onwrite (readable-stream/lib/_stream_writable.js:451:7)
     at WritableState.onwrite (readable-stream/lib/_stream_writable.js:158:5)
     at afterWrite (readable-stream/lib/_stream_writable.js:465:3)
     at onwrite (readable-stream/lib/_stream_writable.js:457:7)
     at WritableState.onwrite (readable-stream/lib/_stream_writable.js:158:5)
     at StreamChopper.ondrain [as _ondrain] (stream-chopper/index.js:59:5)
     at StreamChopper._removeStream (stream-chopper/index.js:182:45)
     at StreamChopper._endStream (stream-chopper/index.js:165:8)
     at StreamChopper._maybeEndTransformSteam (stream-chopper/index.js:137:27)
     at Gzip._stream.on.chunk (stream-chopper/index.js:94:14)
     at emitOne (events.js:121:20)
     at Gzip.emit (events.js:211:7)
     at addChunk (_stream_readable.js:263:12)
     at readableAddChunk (_stream_readable.js:250:11)
     at Gzip.Readable.push (_stream_readable.js:208:10)
     at Gzip.Transform.push (_stream_transform.js:147:32)
     at Zlib.callback (zlib.js:474:14)
```

```
Uncaught Exception: TypeError: Cannot read property 'length' of undefined
    at writeOrBuffer (readable-stream/lib/_stream_writable.js:370:42)
    at StreamChopper.Writable.write (readable-stream/lib/_stream_writable.js:303:11)
    at Client._writevCleaned (elastic-apm-http-client/index.js:276:17)
    at processBatch (elastic-apm-http-client/index.js:249:12)
    at Client._writev (elastic-apm-http-client/index.js:267:3)
    at doWrite (readable-stream/lib/_stream_writable.js:405:97)
    at clearBuffer (readable-stream/lib/_stream_writable.js:501:5)
    at Client.Writable.uncork (readable-stream/lib/_stream_writable.js:317:94)
    at process.nextTick (elastic-apm-http-client/index.js:310:42)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

Both seemingly boiling down to the same bug. This library (I use it in version 8.2.1) calls the `write()` method and skips the second parameter (https://github.com/elastic/apm-nodejs-http-client/blob/v8.2.1/index.js#L276):

```js
  this._chopper.write(chunk, cb)
```

@mcollina asked me to open this issue here in the hope you know better how to reproduce the problem (https://github.com/nodejs/readable-stream/issues/421)

**Comment by SimonSimCity** [comment]
This stack-trace might also be related to it:

```
Uncaught Exception: RangeError: Invalid string length
    at objs.reduce (./node_modules/elastic-apm-http-client/index.js:272:19)
    at Array.reduce (<anonymous>)
    at Client._writevCleaned (./node_modules/elastic-apm-http-client/index.js:271:22)
    at processBatch (./node_modules/elastic-apm-http-client/index.js:249:12)
    at Client._writev (./node_modules/elastic-apm-http-client/index.js:267:3)
    at doWrite (./node_modules/readable-stream/lib/_stream_writable.js:405:97)
    at clearBuffer (./node_modules/readable-stream/lib/_stream_writable.js:501:5)
    at onwrite (./node_modules/readable-stream/lib/_stream_writable.js:451:7)
    at WritableState.onwrite (./node_modules/readable-stream/lib/_stream_writable.js:158:5)
    at afterWrite (./node_modules/readable-stream/lib/_stream_writable.js:465:3)
    at onwrite (./node_modules/readable-stream/lib/_stream_writable.js:457:7)
    at WritableState.onwrite (./node_modules/readable-stream/lib/_stream_writable.js:158:5)
    at StreamChopper.ondrain [as _ondrain] (./node_modules/stream-chopper/index.js:59:5)
    at StreamChopper._removeStream (./node_modules/stream-chopper/index.js:182:45)
    at StreamChopper._endStream (./node_modules/stream-chopper/index.js:165:8)
    at StreamChopper._maybeEndTransformSteam (./node_modules/stream-chopper/index.js:137:27)
    at Gzip._stream.on.chunk (./node_modules/stream-chopper/index.js:94:14)
    at emitOne (events.js:121:20)
    at Gzip.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Gzip.Readable.push (_stream_readable.js:208:10)
    at Gzip.Transform.push (_stream_transform.js:147:32)
    at Zlib.callback (zlib.js:474:14)
```

**Comment by Qard** [comment]
Have you tried updating to the latest release? It's currently at 9.2.0 and that specific code was rewritten awhile ago.

**Comment by SimonSimCity** [comment]
I'll update and reopen this if I see the issue again. It happened just very occasional ...
